/**
 * Config plugin: drops permissions the app never asks for.
 *
 * Three of them end up in the manifest without anyone here wanting them:
 *
 * - RECORD_AUDIO, declared by expo-audio's own manifest. `recordAudioAndroid:
 *   false` in app.json only stops the plugin from ADDING it; the library
 *   declares it anyway and the merger unions the two. Resonus never records:
 *   nothing imports AudioRecorder.
 * - CAMERA, declared by expo-image-picker. Both places that pick an image
 *   (a station's artwork, a playlist cover) call `launchImageLibraryAsync`,
 *   never the camera.
 * - RECEIVE_BOOT_COMPLETED, declared by expo-notifications so that scheduled
 *   notifications survive a reboot. The one notification here is sent on the
 *   spot, never scheduled, so there is nothing to restore after a boot.
 * - SYSTEM_ALERT_WINDOW, which comes in the Expo template's own manifest and is
 *   for React Native's development overlay.
 *
 * None of them is a hole: they are runtime permissions and the app never
 * requests them, so Android would ask first anyway. They are a trust problem.
 * A music player whose store listing reads "can record audio" and "can take
 * pictures" invites exactly the question nobody wants to keep answering.
 *
 * The first three arrive from libraries, so they need an explicit `tools:node
 * ="remove"` to survive the merge. The last is in the app's own manifest and
 * only has to be taken out of it, which leaves debug builds alone: React
 * Native's debug manifest puts it back there, and the dev overlay keeps
 * working while release builds ship without it.
 *
 * android/ is in .gitignore and regenerated by prebuild, so this has to be a
 * plugin: editing the manifest by hand would be lost.
 */
const { withAndroidManifest } = require('@expo/config-plugins');

const TOOLS_NS = 'http://schemas.android.com/tools';

/** Comes from a library: has to be removed at merge time. */
const BLOCKED = [
  'android.permission.RECORD_AUDIO',
  'android.permission.CAMERA',
  'android.permission.RECEIVE_BOOT_COMPLETED',
];

/** Ours to begin with: dropping it from the manifest is enough. */
const DROPPED = ['android.permission.SYSTEM_ALERT_WINDOW'];

module.exports = function withTrimmedPermissions(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    // `tools:node` is meaningless without the namespace declared.
    manifest.$ = { ...manifest.$, 'xmlns:tools': TOOLS_NS };

    const named = (entry) => entry?.$?.['android:name'];
    const kept = (manifest['uses-permission'] ?? []).filter(
      (entry) => !BLOCKED.includes(named(entry)) && !DROPPED.includes(named(entry)),
    );

    manifest['uses-permission'] = [
      ...kept,
      ...BLOCKED.map((name) => ({ $: { 'android:name': name, 'tools:node': 'remove' } })),
    ];
    return cfg;
  });
};
