/**
 * Config plugin: makes the app installable and launchable on Android TV.
 *
 * Four things are needed, and Android is unforgiving about all four. A TV
 * refuses to show an app that does not say it works without a touchscreen; it
 * lists only what carries the leanback launcher category; it wants a banner to
 * draw on its home row; and the Play Store hides anything that *requires*
 * leanback from every phone. So both features are declared `required="false"`:
 * the app then says it can live on a TV without claiming it needs one.
 *
 * **What this does not do** is make the app good on a TV. The screens are
 * built for a finger and are driven here by a remote's arrow keys, which
 * Android maps onto focus. Browsing and playing work; nothing has been laid
 * out for ten feet away. That is a deliberate first step — being installable
 * is what was asked for — and a leanback interface of its own is a project,
 * not a flag.
 *
 * android/ is regenerated by prebuild, so this has to be a plugin: a manifest
 * edited by hand would be lost at the next build.
 */
const fs = require('fs');
const path = require('path');

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

/** The picture a TV draws on its home row. 320×180, as Android requires. */
const BANNER_SOURCE = 'assets/images/android-tv-banner.png';
const BANNER_NAME = 'tv_banner.png';

/** Says a feature may be there without demanding it. Without `required=false`
 *  on leanback the Play Store would hide the app from every phone; without it
 *  on the touchscreen, every TV would hide it. */
function declareFeature(manifest, name) {
  manifest['uses-feature'] = manifest['uses-feature'] ?? [];
  const already = manifest['uses-feature'].some((f) => f.$?.['android:name'] === name);
  if (already) return;
  manifest['uses-feature'].push({ $: { 'android:name': name, 'android:required': 'false' } });
}

const withTvManifest = (config) =>
  withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;
    declareFeature(manifest, 'android.software.leanback');
    declareFeature(manifest, 'android.hardware.touchscreen');

    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);
    application.$['android:banner'] = `@drawable/${BANNER_NAME.replace(/\.png$/, '')}`;

    // The same activity the phone launches, told it is also a TV entry point.
    // A second activity would be a second icon for the same app.
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(mod.modResults);
    for (const filter of activity['intent-filter'] ?? []) {
      const isLauncher = (filter.category ?? []).some(
        (c) => c.$['android:name'] === 'android.intent.category.LAUNCHER',
      );
      if (!isLauncher) continue;
      const hasLeanback = (filter.category ?? []).some(
        (c) => c.$['android:name'] === 'android.intent.category.LEANBACK_LAUNCHER',
      );
      if (!hasLeanback) {
        filter.category.push({ $: { 'android:name': 'android.intent.category.LEANBACK_LAUNCHER' } });
      }
    }
    return mod;
  });

const withTvBanner = (config) =>
  withDangerousMod(config, [
    'android',
    (mod) => {
      const from = path.join(mod.modRequest.projectRoot, BANNER_SOURCE);
      const into = path.join(mod.modRequest.platformProjectRoot, 'app/src/main/res/drawable');
      fs.mkdirSync(into, { recursive: true });
      fs.copyFileSync(from, path.join(into, BANNER_NAME));
      return mod;
    },
  ]);

module.exports = (config) => withTvBanner(withTvManifest(config));
