/**
 * Config plugin: drops permissions the app never asks for.
 *
 * Two of them end up in the manifest without anyone here wanting them:
 *
 * - RECORD_AUDIO, declared by expo-audio's own manifest. `recordAudioAndroid:
 *   false` in app.json only stops the plugin from ADDING it; the library
 *   declares it anyway and the merger unions the two. Resonus never records:
 *   nothing imports AudioRecorder.
 * - CAMERA, declared by expo-image-picker. Both places that pick an image
 *   (a station's artwork, a playlist cover) call `launchImageLibraryAsync`,
 *   never the camera.
 *
 * None of them is a hole: they are runtime permissions and the app never
 * requests them, so Android would ask first anyway. They are a trust problem.
 * A music player whose store listing reads "can record audio" and "can take
 * pictures" invites exactly the question nobody wants to keep answering.
 *
 * RECEIVE_BOOT_COMPLETED used to be dropped as well, expo-notifications'
 * leftover. The wake-up alarm (modules/alarm) needs it now: an alarm set
 * with AlarmManager does not survive a reboot unless something sets it again.
 *
 * Both arrive from libraries, so they need an explicit `tools:node
 * ="remove"` to survive the merge.
 *
 * SYSTEM_ALERT_WINDOW used to be dropped here too, as the Expo template's own
 * leftover for React Native's development overlay. Ride mode's floating
 * player draws over other apps and asks for it (modules/ride-mode), so it
 * stays; the user grants it on the system's own screen, never at install.
 *
 * android/ is in .gitignore and regenerated by prebuild, so this has to be a
 * plugin: editing the manifest by hand would be lost.
 */
const { withAndroidManifest } = require('@expo/config-plugins');

const TOOLS_NS = 'http://schemas.android.com/tools';

/** Comes from a library: has to be removed at merge time. */
const BLOCKED = [
  'android.permission.RECORD_AUDIO',
  'android.permission.CAMERA',
];

module.exports = function withTrimmedPermissions(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    // `tools:node` is meaningless without the namespace declared.
    manifest.$ = { ...manifest.$, 'xmlns:tools': TOOLS_NS };

    const named = (entry) => entry?.$?.['android:name'];
    const kept = (manifest['uses-permission'] ?? []).filter((entry) => !BLOCKED.includes(named(entry)));

    manifest['uses-permission'] = [
      ...kept,
      ...BLOCKED.map((name) => ({ $: { 'android:name': name, 'tools:node': 'remove' } })),
    ];
    return cfg;
  });
};
