/**
 * Config plugin: the launcher shortcuts behind a long press on the app icon.
 *
 * Four of them, static, each a deep link the app already understands or that
 * `src/app/+native-intent.ts` turns into an action:
 *
 *   Shuffle all   resonuls://play/random
 *   Favourites    resonuls://play/favorites
 *   Resume        resonuls://play/resume
 *   Search        resonuls://search
 *
 * Android reads them from `res/xml/shortcuts.xml`, which the main activity
 * points at with an `android.app.shortcuts` meta-data entry. The labels are
 * string resources so the launcher shows them in the phone's language, with
 * French, Spanish and Catalan next to the English. Each icon is an adaptive
 * icon: a Material glyph in the app's green over a white disc, with the same
 * glyph as the monochrome layer so a themed launcher can tint it (Android
 * 13+). Below API 26 the launcher gets the glyph on its own.
 *
 * android/ is in .gitignore and regenerated by prebuild, so this has to be a
 * plugin: files put under res/ by hand would be lost.
 */
const fs = require('fs');
const path = require('path');

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

/** The app's default accent, `DEFAULT_ACCENT` in src/theme/index.ts. */
const ACCENT = '#1DB954';

/**
 * The shortcuts, in the order the launcher ranks them. Each glyph is the
 * Material Icons path on its 24dp canvas, in `<path android:pathData>` form.
 */
const SHORTCUTS = [
  {
    id: 'foryou',
    link: 'resonuls://play/foryou',
    // Material's auto_awesome, the same sparkle the button on Home wears.
    glyph:
      'M19,9l1.25,-2.75L23,5l-2.75,-1.25L19,1l-1.25,2.75L15,5l2.75,1.25L19,9zM11.5,9.5L9,4 6.5,9.5 1,12l5.5,2.5L9,20l2.5,-5.5L17,12 11.5,9.5zM19,15l-1.25,2.75L15,19l2.75,1.25L19,23l1.25,-2.75L23,19l-2.75,-1.25z',
    labels: {
      en: ['For you', 'A mix built from what you play'],
      fr: ['Pour vous', "Un mix d'après ce que vous écoutez"],
      es: ['Para ti', 'Una mezcla a partir de lo que escuchas'],
      ca: ['Per a tu', "Una mescla a partir del que escoltes"],
    },
  },
  {
    id: 'shuffle',
    link: 'resonuls://play/random',
    glyph:
      'M10.59,9.17L5.41,4 4,5.41l5.17,5.17 1.42,-1.41zM14.5,4l2.04,2.04L4,18.59 5.41,20 17.96,7.46 20,9.5V4h-5.5zm0.33,9.41l-1.41,1.41 3.13,3.13L14.5,20H20v-5.5l-2.04,2.04 -3.13,-3.13z',
    labels: {
      en: ['Shuffle all', 'Shuffle the whole library'],
      fr: ['Aléatoire', 'Toute la bibliothèque en aléatoire'],
      es: ['Aleatorio', 'Toda la biblioteca en aleatorio'],
      ca: ['Aleatori', 'Tota la biblioteca en aleatori'],
    },
  },
  {
    id: 'favorites',
    link: 'resonuls://play/favorites',
    glyph:
      'M12,21.35l-1.45,-1.32C5.4,15.36 2,12.28 2,8.5 2,5.42 4.42,3 7.5,3c1.74,0 3.41,0.81 4.5,2.09C13.09,3.81 14.76,3 16.5,3 19.58,3 22,5.42 22,8.5c0,3.78 -3.4,6.86 -8.55,11.54L12,21.35z',
    labels: {
      en: ['Favorites', 'Shuffle your favorites'],
      fr: ['Favoris', 'Vos favoris en aléatoire'],
      es: ['Favoritos', 'Tus favoritos en aleatorio'],
      ca: ['Preferits', 'Els teus preferits en aleatori'],
    },
  },
  {
    id: 'resume',
    link: 'resonuls://play/resume',
    glyph: 'M8,5v14l11,-7z',
    labels: {
      en: ['Resume', 'Pick up where you left off'],
      fr: ['Reprendre', 'Reprendre là où vous étiez'],
      es: ['Reanudar', 'Seguir donde lo dejaste'],
      ca: ['Reprendre', 'Continuar on ho vas deixar'],
    },
  },
  {
    id: 'search',
    link: 'resonuls://search',
    glyph:
      'M15.5,14h-0.79l-0.28,-0.27C15.41,12.59 16,11.11 16,9.5 16,5.91 13.09,3 9.5,3S3,5.91 3,9.5 5.91,16 9.5,16c1.61,0 3.09,-0.59 4.23,-1.57l0.27,0.28v0.79l5,4.99L20.49,19l-4.99,-5zm-6,0C7.01,14 5,11.99 5,9.5S7.01,5 9.5,5 14,7.01 14,9.5 11.99,14 9.5,14z',
    labels: {
      en: ['Search', 'Search the library'],
      fr: ['Rechercher', 'Chercher dans la bibliothèque'],
      es: ['Buscar', 'Buscar en la biblioteca'],
      ca: ['Cerca', 'Cercar a la biblioteca'],
    },
  },
];

/** The languages with their own strings; English is the default `values/`. */
const LOCALES = ['en', 'fr', 'es', 'ca'];

const ANDROID_NS = 'xmlns:android="http://schemas.android.com/apk/res/android"';

/**
 * The glyph as a 108dp vector, scaled to 42dp in the middle so it sits inside
 * the 66dp safe zone an adaptive icon keeps clear of the launcher's mask.
 */
function glyphXml(glyph) {
  return `<?xml version="1.0" encoding="utf-8"?>
<vector ${ANDROID_NS}
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:translateX="33"
        android:translateY="33"
        android:scaleX="1.75"
        android:scaleY="1.75">
        <path
            android:fillColor="${ACCENT}"
            android:pathData="${glyph}" />
    </group>
</vector>
`;
}

function adaptiveIconXml(id) {
  return `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon ${ANDROID_NS}>
    <background android:drawable="@android:color/white" />
    <foreground android:drawable="@drawable/ic_shortcut_${id}_glyph" />
    <monochrome android:drawable="@drawable/ic_shortcut_${id}_glyph" />
</adaptive-icon>
`;
}

function shortcutsXml(pkg) {
  const entries = SHORTCUTS.map(
    ({ id, link }) => `    <shortcut
        android:shortcutId="${id}"
        android:enabled="true"
        android:icon="@drawable/ic_shortcut_${id}"
        android:shortcutShortLabel="@string/shortcut_${id}_short"
        android:shortcutLongLabel="@string/shortcut_${id}_long">
        <intent
            android:action="android.intent.action.VIEW"
            android:data="${link}"
            android:targetPackage="${pkg}"
            android:targetClass="${pkg}.MainActivity" />
    </shortcut>`,
  );
  return `<?xml version="1.0" encoding="utf-8"?>
<shortcuts ${ANDROID_NS}>
${entries.join('\n')}
</shortcuts>
`;
}

/** Android string syntax: an apostrophe or a quote ends the string otherwise. */
function escapeAndroid(text) {
  return text.replace(/([@?'"\\])/g, '\\$1').replace(/&/g, '&amp;').replace(/</g, '&lt;');
}

function stringsXml(locale) {
  const items = SHORTCUTS.flatMap(({ id, labels }) => {
    const [short, long] = labels[locale];
    return [
      `    <string name="shortcut_${id}_short">${escapeAndroid(short)}</string>`,
      `    <string name="shortcut_${id}_long">${escapeAndroid(long)}</string>`,
    ];
  });
  return `<?xml version="1.0" encoding="utf-8"?>
<resources>
${items.join('\n')}
</resources>
`;
}

/** Every file the plugin writes, relative to `res/`. */
function resourceFiles(pkg) {
  const files = { 'xml/shortcuts.xml': shortcutsXml(pkg) };
  for (const { id, glyph } of SHORTCUTS) {
    files[`drawable/ic_shortcut_${id}_glyph.xml`] = glyphXml(glyph);
    // The glyph on its own where adaptive icons do not exist yet (API 25).
    files[`drawable/ic_shortcut_${id}.xml`] = glyphXml(glyph);
    files[`drawable-v26/ic_shortcut_${id}.xml`] = adaptiveIconXml(id);
  }
  for (const locale of LOCALES) {
    const dir = locale === 'en' ? 'values' : `values-${locale}`;
    files[`${dir}/shortcuts.xml`] = stringsXml(locale);
  }
  return files;
}

function withShortcutResources(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const res = await AndroidConfig.Paths.getResourceFolderAsync(cfg.modRequest.projectRoot);
      for (const [file, contents] of Object.entries(resourceFiles(cfg.android.package))) {
        const target = path.join(res, file);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, contents);
      }
      return cfg;
    },
  ]);
}

function withShortcutsMetaData(config) {
  return withAndroidManifest(config, (cfg) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(cfg.modResults);
    const rest = (activity['meta-data'] ?? []).filter(
      (entry) => entry?.$?.['android:name'] !== 'android.app.shortcuts',
    );
    activity['meta-data'] = [
      ...rest,
      { $: { 'android:name': 'android.app.shortcuts', 'android:resource': '@xml/shortcuts' } },
    ];
    return cfg;
  });
}

module.exports = function withShortcuts(config) {
  return withShortcutsMetaData(withShortcutResources(config));
};
